# Generated by Django 4.1.4 on 2022-12-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Thing',
        ),
    ]
